# Generated by Django 4.0.6 on 2022-07-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventControler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
