# Generated by Django 4.0.6 on 2022-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_icon', models.CharField(max_length=50, verbose_name='')),
                ('service_title', models.CharField(max_length=50)),
                ('service_des', models.TextField(max_length=50)),
            ],
        ),
    ]
