version: "3"

services:
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit123
    ports:
      - "5672:5672"
    networks:
      - postgres
    restart : unless-stopped

networks:
  postgres:
    driver: bridge
